# Generated by Django 5.2.17 on 2026-10-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
